
name: SQL Lint
on:
  push:
    paths: ["sql/**", ".sqlfluff"]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install sqlfluff==3.0.7
      - run: sqlfluff lint sql
